Add Support for Parsing APS_REGION Environment Variable
petrbroz/svf-utils pull request #83
Opened 2024-06-04 12:18 UTC by yasotnik

Addresses #82 

I have made the following updates:

- Adds parsing of `APS_HOST` and `APS_REGION` (under the hood only region one is used, added host so we do not need to change the order of parameters in `SvfReader.FromDerivativeService`)
- Updates `README.md`

I have tested the fix with all the _samples_.

Now, I understand that this fix should have probably been done in the new `aps_sdk/autodesk-sdkmanager` which would make more sense from my point of view to store `region`, `host`, etc in the manager instead of passing it down to specific functions. 
On the other hand, this way we can quickly add support for the region and think about adding it to `autodesk-sdkmanager` once it is stable.

P.S.: I also should have probably refactored `downloader` in `f2d` because it is very close to the `svf` one and moved it to `common` or something along that. Lmk if I should do it. But again, I would like to keep the fix as small as possible. 

Thank you!

2024-07-08 08:11 UTC, petrbroz commented
Thanks @yasotnik, the PR looks good. The only thing I'm not sure about is the handling of custom APS hosts. Let me comment directly on the code section I'm referring to.

2024-07-08 08:13 UTC, petrbroz commented on samples/remote-svf-to-gltf.js
> +        const derivatives = await getSvfDerivatives(urn, APS_CLIENT_ID, APS_CLIENT_SECRET, APS_REGION);
If we're already supporting custom APS hosts for `SvfReader.FromDerivativeService`, we should probably support them in this method as well?

2024-07-08 08:15 UTC, petrbroz commented on src/f2d/downloader.ts
> +        this.host = 'developer.api.autodesk.com'
This is a bit misleading. Why are we accepting a `host` parameter in the constructor if we're simply ignoring it here? Wouldn't it make sense to change this line to something like `this.host = host || 'developer.api.autodesk.com';`?

2024-07-08 08:15 UTC, petrbroz commented on src/svf/downloader.ts
> +        this.host = 'developer.api.autodesk.com'
Same as above.

2024-07-08 08:20 UTC, petrbroz requested changes
Complete the support for custom APS hosts. Even if the current version of the APS SDK does not support this feature, we should at least propagate the custom host setting all the way to the SDK calls. Currently the code is a bit misleading as it seems to ignore host parameters passed into constructors.

2024-07-08 11:53 UTC, yasotnik commented
> Complete the support for custom APS hosts. Even if the current version of the APS SDK does not support this feature, we should at least propagate the custom host setting all the way to the SDK calls. Currently the code is a bit misleading as it seems to ignore host parameters passed into constructors.

You are right. But as far as I understand there is no way to pass it to the APS SDK. I can add it as a parameter to `getSvfDerivatives`.

I have another question, do you happen to know if APS SDK is open-source? I looked into it for some time and could help to integrate custom `host` and `region` support.
The only thing I found is https://github.com/autodesk-platform-services/aps-sdk-node but `autodesk-sdkmanager` is a separate package https://www.npmjs.com/package/@aps_sdk/autodesk-sdkmanager

Something like:
```javascript
const sdkManager = SdkManagerBuilder.create().addApsConfiguration(host, region).build();
```

2024-09-11 11:13 UTC, petrbroz commented
Thanks @yasotnik. I've just added support for custom regions as part of another set of changes (released in v5.0.5).

2024-09-11 11:13 UTC, closed without merging